### ISSUE TITLE
Not compatible with Thunderbird 78

### ISSUE THREAD

**Issue by fa-ribeiro** [moisseev/rspamd-spamness#22]
Rspamd-spamness is incompatible with Thunderbird 78.1.0.
Any quick fix?

**Comment by moisseev** [comment]
No, quick fix is not possible, `rspamd-spamness` is a XUL extension and `Thunderbird 78` doesn't support XUL.
Support for "legacy" add-ons was removed in Thunderbird 74beta. The only way is rewriting the add-on using modern `MailExtensions` API, but currently I have no plans for this.

**Comment by realizelol** [comment]
Mozilla nay MZLA Technologies Corporation has removed the blockade to auto update to version 78.x.x.

Today my Thunderbird was updated to 78, even I also had have another 2 addons which aren't compatible to version 78.

Steps to go back to the old version:
- Download the latest 68 version (actually 68.12):
   [https://archive.mozilla.org/pub/thunderbird/releases/68.12.0/](https://archive.mozilla.org/pub/thunderbird/releases/68.12.0/)
- Then run cmd and enter this command:
   `"C:\Program Files (x86)\Mozilla Thunderbird\Thunderbird" -allow-downgrade`

After you've done that you could use back the old version again, but please be noted I don't take any responsiblity of lost data.

best regards
realizelol

**Comment by zertrin** [comment]
Same here, with 3 add-ons incompatible. Luckily I had a recent backup of my TB profile for before the upgrade.

Downgrading from TB78 to TB68 without restoring a backup of the profile should work, but the address book will be lost (because TB78 migrated it to another format).
In my case I restored the backup of the previous profile before reinstalling TB68 and everything was back to normal... 

... well... almost:

**before** uninstalling TB78, I strongly suggest to go to the settings and disable automatic updates. Otherwise as soon as TB68 is reinstalled, it will happily re-upgrade to TB78 ☹️. _(been there, done that...)_

To fully prevent the automatic upgrade checks, for Windows at least there is a trick by adding a registry entry (reproduced below) that I found [here](http://forums.mozillazine.org/viewtopic.php?f=39&t=3063508) (and that worked for me).

But note: DO NOT open the `Help > About` menu! Apparently opening this menu also triggers an update check even with the automatic update check disabled!

> Exit Thunderbird.
> 
> Type 'Run' in search and select 'Run' app
> In 'Run' app type regedit and click on Ok
> HKEY_LOCAL_MACHINE\Software\Policies
> Create new subkey called 'Mozilla'
> HKEY_LOCAL_MACHINE\Software\Policies\Mozilla
> Then create new subkey called 'Thunderbird'
> HKEY_LOCAL_MACHINE\Software\Policies\Mozilla\Thunderbird
> On the right, create a new 32-Bit DWORD value DisableAppUpdate.
> Note: Even if you are running 64-bit Windows you must still create a 32-bit DWORD value.
> Set its value to 1.
> 
> Start Thunderbird
> 
> Menu icon > Options > Options > Advanced > 'Updates' tab Thunderbird updates It will state current version number. Options are removed and replaced by: 'Updates disabled by your system administrator'
> 
> To undo the change, remove the DisableAppUpdate 32-bit DWORD value you have created, then restart Thunderbird.

**Comment by realizelol** [comment]
@zertrin 

Thank you very much !! I didn't thought about that gimmick.

This is a batch script which could be run via "rightclick -> run as administrator":
```
powershell New-Item -Path "HKLM:\Software\Policies\Mozilla\Thunderbird" -Force -EA SilentlyContinue
reg query "HKLM:\Software\Policies\Mozilla\Thunderbird" /v "DisableAppUpdate" goto update || goto install
:install
powershell New-ItemProperty -Path "HKLM:\Software\Policies\Mozilla\Thunderbird" -Name "DisableAppUpdate" -PropertyType Dword -Value 1
:update
powershell Set-ItemProperty -Path "HKLM:\Software\Policies\Mozilla\Thunderbird" -Name "DisableAppUpdate" -Value 1
gpupdate /force /boot
```
(Please note: that the "/boot" flag on gpupdate will force a logout on Win7/Win2008R2 or previous versions.)
--> This will create the registry key (folders) and create or update the value of "DisableAppUpdate" to 1

To remove just run this in an administrative cmd or powershell (WIN + X (together) then A):
`powershell Remove-ItemProperty -Path "HKLM:\Software\Policies\Mozilla\Thunderbird" -Name DisableAppUpdate`
`gpupdate /force /boot` and restart thunderbird or just do a reboot of your pc.


best regards
realizelol

**Comment by realizelol** [comment]
I think now it's very difficult to stay on the old version:
[CVE-2020-15673](https://www.mozilla.org/en-US/security/advisories/mfsa2020-44/#CVE-2020-15673)

So hopefully there will be a rewritten code soon. :(

best regards
realizelol

**Comment by Bommel24** [comment]
This plugin works in Thunderbird 78: https://github.com/friedPotat0/Spam-Scores

**Comment by realizelol** [comment]
Thank you moisseev, the actual master (2.0.0a1) is working like a charm in Thunderbird 78.7.1!
